language: php

php:
 - 5.3
 - 5.4

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c phpunit.dist.xml

after_script:
  - ./vendor/bin/coveralls
